### ISSUE TITLE
ArrayTypeDeclaration.items() does not work for array types defined by "[]" expression.

### ISSUE THREAD

**Issue by KonstantinSviridov** [raml-org/raml-js-parser-2#360]
If one defines an array type in a way like ```MyArrayType: MyComponentType[]```, the `items()` method returns `null` for corresponding ArrayTypeDeclaration instance.

**Comment by ddenisenko** [comment]
Fixed.

**Comment by ddenisenko** [comment]
Note: `items()` returns only what actually is in AST, if there is no `items` anonymous type node inside, method returns nothing, as it is not a good idea to emulate unexisting TypeDeclaration node from type expression.

In order to make the access to the existing type declarations node from an array type more accessible, `findComponentTypeDeclaration` helper method was added, which return component type declaration if that type declaration actually exists.

**Comment by domarmstrong** [comment]
This still doesn't work for scalar types like `string[]`. items() and findComponentTypeDeclaration() both return null. I would expect a StringTypeDeclaration to be returned.
