### ISSUE TITLE
Discriminators are not identifying existing subtypes when defined in an external file

### ISSUE THREAD

**Issue by iamerico** [raml-org/raml-js-parser-2#789]
The subtypes have been defined in the file **example-library.raml:**
```
#%RAML 1.0 Library
usage:

types:
  Person:
    type: object
    discriminator: kind
    properties:
      name: string
      kind: string
  Employee:
    type: Person
    discriminatorValue: employee # override default
    properties:
      employeeId: string
  User:
    type: Person
    discriminatorValue: user # override default
    properties:
      userId: string
```
Then _Discriminators: kind_ are not identifying existing subtypes:
```
#%RAML 1.0
title: Discriminator 
mediaType: application/json
uses:
  model: example-library.raml  
  
/persons{id}:
    get:
     responses:
      200:
        body:
          type: model.Person[]
          example: # single request body example
            value: # needs to be declared since instance contains a 'value' property
              - name: A User
                userId: "111"
                kind: user
              - name: An Employee
                employeeId: "222"
                kind: employee
            strict: false
```

### Message Error:
> None of the 'model.Person' type known subtypes declare 'user' as value of discriminating property 'kind'. at (17, 17)
>None of the 'model.Person' type known subtypes declare 'employee' as value of discriminating property 'kind'. at (20, 17)

**Comment by KonstantinSviridov** [comment]
Hi, @iamerico !

Some time ago we fixed a similar issue. Now we can not reproduce your issue with the 1.1.30 version.
Could you, please, check your parser version.

Here is a smple project which depends on 1.1.30 and does not produce errors for your RAML code:
[issue789.zip](https://github.com/raml-org/raml-js-parser-2/files/1300501/issue789.zip)
You may check it by excuting
```
npm install
npm run test
```

Regards,
Konstantin

**Comment by iamerico** [comment]
Hi, Konstantin
If it is true with the last update, this error will not be reproduced.

Regards,
Ignacio

**Comment by iamerico** [comment]
Hi @KonstantinSviridov ,
We can still reproduce the error, but ONLY if we get the errors from the `toJson` using the `rootNodeDetails` property like this:

```
parser.loadApi(file, {
	attributeDefaults: false,
	rejectOnErrors: false
}).then(function (api) {
	api = api.expand(true);
			
  var json = api.toJSON({
  	serializeMetadata: false,
  	dumpSchemaContents: false,
  	rootNodeDetails: true
  });

  console.log("Expected empty, but found: ", json.errors);
}
```

**Comment by KonstantinSviridov** [comment]
That's very strange. As the example has `strict` property set to `false`, its value must be completely ignored by validator. And I do see (by inserting console messages into the validator code) that it is ignored in your case.

I'm executing the following script:
```js
console.log("issue 789");
var parser = require("raml-1-parser");
var path = require("path");
var apiPath = path.resolve(__dirname,'../RAML/issue789/api.raml');
parser.loadApi(apiPath, {
	attributeDefaults: false,
	rejectOnErrors: false
}).then(function (api) {
	api = api.expand(true);
			
  var json = api.toJSON({
  	serializeMetadata: false,
  	dumpSchemaContents: false,
  	rootNodeDetails: true
  });

  console.log("Expected empty, but found: ", json.errors);
});
```
and get the following output:
```
issue 789
Expected empty, but found:  []
```

Thus, my only idea is that you're using incorrect file path. Could you, please, check my updated  example which has exactly the same code as above. After unzipping it to a separate folder execute the following commands:
```
npm install
npm run test
```
[issue789-2.zip](https://github.com/raml-org/raml-js-parser-2/files/1325719/issue789-2.zip)



The only problem I see is that empty value is not accepted with `strict` set to `false`. Such example
```yaml
          example:
            value:
            strict: false
```
causes "Expected type 'array' but got 'object'" while it must not. So thanks for helping to discover this issue.

**Comment by iamerico** [comment]
Hi, 
I updated your example and just changed the `strict` to `true`, and corrected the references to the types.
[issue789-updated.zip](https://github.com/raml-org/raml-js-parser-2/files/1334756/issue789-updated.zip)
You should be able to unzip and `run npm install` and `npm run test`, and then get:
```
issue 789
Expected empty, but found:  [ { code: 'INCORRECT_DISCRIMINATOR',
    message: 'None of the \'model.Person\' type known subtypes declare \'user1\' as value of discriminating property \'kind\'.',
    path: 'api.raml',
    line: undefined,
    column: undefined,
    position: undefined,
    range: { start: [Object], end: [Object] },
    isWarning: true },
  { code: 'INCORRECT_DISCRIMINATOR',
    message: 'None of the \'model.Person\' type known subtypes declare \'employee1\' as value of discriminating property \'kind\'.',
    path: 'api.raml',
    line: undefined,
    column: undefined,
    position: undefined,
    range: { start: [Object], end: [Object] },
    isWarning: true } ]
```

**Comment by KonstantinSviridov** [comment]
Thank you very much.

I finally got it with your example. It's not the same issue as before as it is only revealed with `true` passed to `.expand()`.

**Comment by KonstantinSviridov** [comment]
Hi @iamerico !

The fix is now in the 'develop' brancehs set. It will be brought to `master` and npm with the next release.

Regards,
Konstantin
